spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/epet?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: 615879220
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
        content-type: text/html
    cache: false
    suffix: .html
    prefix: classpath:/templates/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.bdqn.pojo


